- name: Deploy RunCalc App
  hosts: web
  become: true

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Remove existing container
      docker_container:
        name: runcalc
        state: absent
      ignore_errors: yes

    - name: Run new container
      docker_container:
        name: runcalc
        image: "{{ docker_image }}:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"